name = "PuiseuxPolynomials"
uuid = "f53aee1f-40be-4d16-bc74-7d339eee78ec"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.9"

[deps]
LaTeXStrings= "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LaurentPolynomials = "10b2801c-d482-41ed-a506-4a825c59e3da"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModuleElts = "4249f315-58d4-4c46-b324-3577fc7dfca0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
LaTeXStrings= "1.4"
LaurentPolynomials = "0.1.7"
LinearAlgebra = "1"
ModuleElts = "0.1.4"
OrderedCollections = "1"
Reexport = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
